### ISSUE TITLE
[Stackable Items | Feature Request]: Add music discs.

### ISSUE THREAD

**Issue by Ynaught** [gabriel-pinheiro/datapacks#10]
Music discs currently are only a stack size of one. This is very annoying for the sake of bundles. If you could stack 64 of the same music disc together, that means you could fit a bunch of different music discs inside a singular bundle.

**Comment by gabriel-pinheiro** [comment]
Nice suggestion @Ynaught ! I'll add this today

**Comment by gabriel-pinheiro** [comment]
Hey @Ynaught ! Music discs have been added, you can download v1.1.1 from here:
https://modrinth.com/datapack/stackable-items/changelog

Just a reminder: After updating, the new discs you acquire will be stackable by default. For the ones you already have, just drop them on the ground and pick them up again and they'll be updated by the datapack :)

Let me know if it works and I'll close the issue!

**Comment by Ynaught** [comment]
Saw the upload. Will be testing it shortly/later today before closing the issue report to be sure no issues came from the update. ^u^

**Comment by Ynaught** [comment]
Can verify. Works perfectly. Only additional feature I would request is increasing the stack size of ender-pearls from 16 to 64 to better match windbursts and blaze powder, since there is theming similarities between these items. Regardless though, that's a separate topic so I'll close this report now as complete.

**Comment by gabriel-pinheiro** [comment]
Thanks for the return, @Ynaught !

Ender Pearls are already supported, but with the same caveat as the discs: New pearls you get after installation will already stack to 64. Older pearls will need to be dropped on the ground for Stackable Items to fix them
