### ISSUE TITLE
Not Teleporting

### ISSUE THREAD

**Issue by Mortycio** [gabriel-pinheiro/datapacks#3]
The mod works correctly when used individually, but in my world created with numerous other mods, it doesn't work. How do I figure out which mod is causing the incompatibility?

**Comment by gabriel-pinheiro** [comment]
Hey @Mortycio !

I can help you with that! Can you fill those questions to help me with the troubleshooting? I'll help you in a bit

- Are you using it as a Datapack (.zip file) or Mod (.jar file)?
- If you're using as a mod, which modloader are you using (Fabric, Forge, Quilt)?
- What Minecraft version are you using (1.20 ~ 1.20.4)?
- What other mods are installed?
- If I got it right, you could create the portal but teleporting doesn't work, right?

**Comment by Mortycio** [comment]
> Hey @Mortycio !
> 
> I can help you with that! Can you fill those questions to help me with the troubleshooting? I'll help you in a bit
> 
> * Are you using it as a Datapack (.zip file) or Mod (.jar file)?
> * If you're using as a mod, which modloader are you using (Fabric, Forge, Quilt)?
> * What Minecraft version are you using (1.20 ~ 1.20.4)?
> * What other mods are installed?
> * If I got it right, you could create the portal but teleporting doesn't work, right?

- I'm using it both ways: as a mod (uploaded into the mods folder) and as a datapack (uploaded into the datapacks folder, as specified for "Existing SinglePlayer World" on your page).
- I'm using Fabric.
- I'm using version 1.20.1.
- I'm attaching a .txt file with the mods I'm using. (I apologize, I simply copy-pasted the list from the log.)
- Yes, you're right. Everything works, but when I go into the portal, nothing happens.

[mods list.txt](https://github.com/gabriel-pinheiro/datapacks/files/14726411/mods.list.txt)

**Comment by Mortycio** [comment]
You're amazing! It works! Thank you so much for the help and for the advice on that other mod
