### ISSUE TITLE
Volume Too High!

### ISSUE THREAD

**Issue by Mortycio** [gabriel-pinheiro/datapacks#4]
The volume is too high! Is there a way to manually lower it in some config file?

**Comment by gabriel-pinheiro** [comment]
I totally agree!! I mostly tested on mute so it wasn't adjusted very well
It's already fixed on v1.3.5 (I attached it below), it'll most likely be released on modrinth/curseforge on Saturday but you can already download it from here. Let me know if you need any help!
[Datapack: Warp Portals v1.3.5.zip](https://github.com/gabriel-pinheiro/datapacks/files/14764939/Warp.Portals.v1.3.5.zip)
[Mod: warp-portals-1.3.5.jar](https://cdn.codetunnel.net/notnull/warp-portals-1.3.5.jar)

**Comment by Mortycio** [comment]
Thanks, now the volume is slightly lower, but for me, it's still too high... Is there a way to adjust the volume in the mod settings?

**Comment by gabriel-pinheiro** [comment]
@Mortycio version v1.3.9 is available with the option to disable sounds. It'll be documented on 1.4 but, until then, you can see the new menu with:
```
/function warp_portals:config
```

You can download the new version here:
[https://modrinth.com/datapack/warp-portals](https://modrinth.com/datapack/warp-portals)

Let me know if it works!

**Comment by Mortycio** [comment]
> @Mortycio version v1.3.9 is available with the option to disable sounds. It'll be documented on 1.4 but, until then, you can see the new menu with:
> 
> ```
> /function warp_portals:config
> ```
> 
> You can download the new version here: https://modrinth.com/datapack/warp-portals
> 
> Let me know if it works!

Great! Yes, it works, even though it’s a bit inconvenient since to use that command on my server I have to open the world in LAN to activate the commands. 

I would really like the presence of a way to adjust the volume since the teleportation sound is cool but too loud. 
If it’s not in the plans, I’m satisfied with this command to completely disable it.

**Comment by gabriel-pinheiro** [comment]
That's a great idea (volume control instead of on/off)! I'll add it in the next version

**Comment by gabriel-pinheiro** [comment]
Hey @Mortycio ! v1.3.10 added volume control, let me know if it works!

**Comment by Mortycio** [comment]
> Hey @Mortycio ! v1.3.10 added volume control, let me know if it works!

It doesn't work.. I updated the mod to version 1.3.10, activated the commands in the world, and executed the command `/function warp_portals:config/teleport_sound_decrease` but nothing happens. In chat, the mod alert `executed command 33 from function "warp_portals:config/teleport_sound_decrease"` appears and nothing else. Moreover, nothing changes if I execute the command multiple times in an attempt to decrease the volume further.

P.S. for now, the only way to tweak the mod settings is through commands in chat, which is quite inconvenient. I don't even have a .json or text file to edit in the config folder on the computer. It would be convenient if there was the possibility to edit the settings directly from the 'Mods' menu in Minecraft as shown in the attached screenshot.

![Screenshot 2024-04-30 193704](https://github.com/gabriel-pinheiro/datapacks/assets/113641947/4f2a0107-8f8f-4a97-b2f7-af30d969146b)

**Comment by gabriel-pinheiro** [comment]
Hey @Mortycio !

I'm taking a look at your previous issue where you sent me your setup, its the same, right?
I just tested it on 1.20.1 with fabric and it seems to work for me. I have a few hypothesis:
- You mentioned you tried warp portals both as a mod and datapack. Could you make sure the datapack was property deleted when you loaded it as a mod? I'll make the instructions clearer on that but it must be loaded either as a mod, either as a datapack but not both at the same time.
- When you click the [-] and [+] in the menu does the text change from High to Medium, Low and Off?
- When the volume is "Off", can you hear the teleportation sound?

A test that would help me troubleshoot would be executing the sound commands manually to check if the volume difference is present there, these are the commands used to play the sound at different levels:
- High: `/playsound minecraft:entity.enderman.teleport player @a ~ ~ ~ 0.3`
- Medium: `/playsound minecraft:entity.enderman.teleport player @a ~ ~ ~ 0.2` 
- Low: `/playsound minecraft:entity.enderman.teleport player @a ~ ~ ~ 0.1`

Minecraft's volume control is very uneven, maybe the low volume should be even lower and more levels added below (Lower and Lowest). How about:
- High: `/playsound minecraft:entity.enderman.teleport player @a ~ ~ ~ 0.3`
- Medium: `/playsound minecraft:entity.enderman.teleport player @a ~ ~ ~ 0.1` 
- Low: `/playsound minecraft:entity.enderman.teleport player @a ~ ~ ~ 0.03`
- Lower: `/playsound minecraft:entity.enderman.teleport player @a ~ ~ ~ 0.01`
- Lowest: `/playsound minecraft:entity.enderman.teleport player @a ~ ~ ~ 0.003`

```
P.S. for now, the only way to tweak the mod settings is through commands in chat, which is quite inconvenient. I don't even have a .json or text file to edit in the config folder on the computer. It would be convenient if there was the possibility to edit the settings directly from the 'Mods' menu in Minecraft as shown in the attached screenshot.
```
I'd love to add that feature but, at the moment, Warp Portals is developed as a Datapack and ported to a Mod "automatically". This means that I can't add features not supported by datapacks without maintaining two versions of Warp Portals.
Unfortunaly minecraft doesn't provide a better way to add menus to datapacks :/

When warp portals is more "feature complete", I maay create a standalone mod with better settings and support for more features (two-way portals, inter-dimentional portals, particle settings, etc).

**Comment by Mortycio** [comment]
> Hey @Mortycio !
> 
> I'm taking a look at your previous issue where you sent me your setup, its the same, right? I just tested it on 1.20.1 with fabric and it seems to work for me. I have a few hypothesis:
> 
> * You mentioned you tried warp portals both as a mod and datapack. Could you make sure the datapack was property deleted when you loaded it as a mod? I'll make the instructions clearer on that but it must be loaded either as a mod, either as a datapack but not both at the same time.
> * When you click the [-] and [+] in the menu does the text change from High to Medium, Low and Off?
> * When the volume is "Off", can you hear the teleportation sound?
> 
> A test that would help me troubleshoot would be executing the sound commands manually to check if the volume difference is present there, these are the commands used to play the sound at different levels:
> 
> * High: `/playsound minecraft:entity.enderman.teleport player @a ~ ~ ~ 0.3`
> * Medium: `/playsound minecraft:entity.enderman.teleport player @a ~ ~ ~ 0.2`
> * Low: `/playsound minecraft:entity.enderman.teleport player @a ~ ~ ~ 0.1`
> 
> Minecraft's volume control is very uneven, maybe the low volume should be even lower and more levels added below (Lower and Lowest). How about:
> 
> * High: `/playsound minecraft:entity.enderman.teleport player @a ~ ~ ~ 0.3`
> * Medium: `/playsound minecraft:entity.enderman.teleport player @a ~ ~ ~ 0.1`
> * Low: `/playsound minecraft:entity.enderman.teleport player @a ~ ~ ~ 0.03`
> * Lower: `/playsound minecraft:entity.enderman.teleport player @a ~ ~ ~ 0.01`
> * Lowest: `/playsound minecraft:entity.enderman.teleport player @a ~ ~ ~ 0.003`
> 
> ```
> P.S. for now, the only way to tweak the mod settings is through commands in chat, which is quite inconvenient. I don't even have a .json or text file to edit in the config folder on the computer. It would be convenient if there was the possibility to edit the settings directly from the 'Mods' menu in Minecraft as shown in the attached screenshot.
> ```
> 
> I'd love to add that feature but, at the moment, Warp Portals is developed as a Datapack and ported to a Mod "automatically". This means that I can't add features not supported by datapacks without maintaining two versions of Warp Portals. Unfortunaly minecraft doesn't provide a better way to add menus to datapacks :/
> 
> When warp portals is more "feature complete", I maay create a standalone mod with better settings and support for more features (two-way portals, inter-dimentional portals, particle settings, etc).

- I only have the mod, not the datapack.
- I don’t have any menu to interact with, so clicking [-] or [+] does nothing.
- If I turn off the sound using the command `/function warp_portals:config/portal_sound_off`, the chat message appears 
   _turned portal sounds off 
   executed command 31 from function 
   “warp_portals:config/portal_sound_off”_ 
   but the sound remains active and very loud (before it used to turn off); I attach a screenshot of the chat message.
- Trying to execute those three commands, I can hear the differences in sound intensity; among other things, is this the sound I should hear during teleportation or is it just a sound for testing? Because what I hear when I use a portal is totally different.
- For these five sounds, the same thing applies as I said for the other three: I hear the differences but it is still different from the sound I hear when I teleport.

![Screenshot 2024-05-01 010007](https://github.com/gabriel-pinheiro/datapacks/assets/113641947/9d33a4d5-2807-49ad-b5fb-b802c6fc47fd)

**Comment by gabriel-pinheiro** [comment]
Ohhh that's weird, the menu is totally broken, it's supposed to be like this:
![image](https://github.com/gabriel-pinheiro/datapacks/assets/56726395/108f8d71-495b-4bfa-bbaf-65c7a5b504f9)
(When you execute the command in the chat, the following menu would appear and you can change settings without using any commands, just clicking in the chat)

Example:
https://github.com/gabriel-pinheiro/datapacks/assets/56726395/7407f93c-d1d8-452c-be14-8494596213d1

```
Trying to execute those three commands, I can hear the differences in sound intensity; among other things, is this the sound I should hear during teleportation or is it just a sound for testing? Because what I hear when I use a portal is totally different.
```
Yeah, that's the sound it's supposed to play, the other longer sound is used only when teleportation takes more than ~1 second. If both are playing there might be two active versions at the same time..

What's the return of the command `/datapack list`? By any chance, are there two .jars of the mod?

**Comment by Mortycio** [comment]
> Ohhh that's weird, the menu is totally broken, it's supposed to be like this: ![image](https://private-user-images.githubusercontent.com/56726395/327023551-108f8d71-495b-4bfa-bbaf-65c7a5b504f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NjM5MDgsIm5iZiI6MTcxNDU2MzYwOCwicGF0aCI6Ii81NjcyNjM5NS8zMjcwMjM1NTEtMTA4ZjhkNzEtNDk1Yi00YmZhLWJiYWYtNjVjN2E1YjUwNGY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDExNDAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkOWQ0ODY1YWFmYjNhYjgyMjk0M2U5OThiNjEzZDIzYzZkNDE4NWZhOTk5ZmRkYjI2MTU5MDExOWYzOGMzODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wEREfD7KQM5l1wVYvCRkbeQbdHR2DRbMilPncBtxJvA) (When you execute the command in the chat, the following menu would appear and you can change settings without using any commands, just clicking in the chat)
> 
> Example: https://github.com/gabriel-pinheiro/datapacks/assets/56726395/7407f93c-d1d8-452c-be14-8494596213d1
> 
> ```
> Trying to execute those three commands, I can hear the differences in sound intensity; among other things, is this the sound I should hear during teleportation or is it just a sound for testing? Because what I hear when I use a portal is totally different.
> ```
> 
> Yeah, that's the sound it's supposed to play, the other longer sound is used only when teleportation takes more than ~1 second. If both are playing there might be two active versions at the same time..
> 
> What's the return of the command `/datapack list`? By any chance, are there two .jars of the mod?

Oh, there it is! I understood what the error was: by running the `/datapack list` command I noticed that the datapack of the mod in version 1.3.3 was left and from there I realized that there were two datapacks folders, one in the profile folder, and one in the world folder. 
Now, having deleted it, the menu appears correctly and works. 
But it seems to me that I have understood that the teleport sound is connected to the Minecraft music setting, and not to the environment or hostile creatures setting… in fact I couldn’t hear it because I have Minecraft music disabled heh 
It would seem too much to ask you to connect the sounds of the mod to one of these last two settings since you have already done so much, so I will try to get used to Minecraft music from now on 😅

**Comment by gabriel-pinheiro** [comment]
Hey Mortycio!

I'm glad it worked!

```
But it seems to me that I have understood that the teleport sound is connected to the Minecraft music setting, and not to the environment or hostile creatures setting… in fact I couldn’t hear it because I have Minecraft music disabled
```
Hmm it should be connected to the "Players" volume control, is that slider off?

```
It would seem too much to ask you to connect the sounds of the mod to one of these last two settings since you have already done so much, so I will try to get used to Minecraft music from now on 😅
```
Don't worry about it! Receiving feedback and suggestions from users is always amazing 😄 

Let me know if it worked with "Music" off and "Players" on!

**Comment by Mortycio** [comment]
> Hey Mortycio!
> 
> I'm glad it worked!
> 
> ```
> But it seems to me that I have understood that the teleport sound is connected to the Minecraft music setting, and not to the environment or hostile creatures setting… in fact I couldn’t hear it because I have Minecraft music disabled
> ```
> 
> Hmm it should be connected to the "Players" volume control, is that slider off?
> 
> ```
> It would seem too much to ask you to connect the sounds of the mod to one of these last two settings since you have already done so much, so I will try to get used to Minecraft music from now on 😅
> ```
> 
> Don't worry about it! Receiving feedback and suggestions from users is always amazing 😄
> 
> Let me know if it worked with "Music" off and "Players" on!

Yes, that's true, the sound is linked to the "Players" volume and not to the "Music". 
However, currently in my world, I have two portals, and I only hear the teleportation sound with one of them. 
Tomorrow I will do further tests 👍

**Comment by Mortycio** [comment]
Ok, I didn’t understand the reason but the sound is triggered most of the time, not always. Sometimes it doesn’t start at all. 
I tried in creative mode by placing blocks around the portal until it was completely covered, leaving only a 2x2 corridor, and in that case the sound is not triggered. 
But I’m not sure this is the cause… anyway it’s not a problem at all, it’s just to let you know :)
