### ISSUE TITLE
Feature Request: Warp Portals Other Dimensions

### ISSUE THREAD

**Issue by Parilia** [gabriel-pinheiro/datapacks#6]
I would love if we could use warp portals in other dimensions, I can see why between dimensions could be an issue but if that could be possible that would be awesome too.

**Comment by gabriel-pinheiro** [comment]
Hey @Parilia ! Thanks for the suggestion, I'll add support for the nether and the end in the next versions with the new config menu. Not sure if it should be default on or default off though.. What are your thoughts on that? (I'd love to hear more from the users about that, if anyone else is reading this feel free to add to the discussion)

And yeah, between dimensions is trickier for older versions (<1.20.2), I'll add it to the ideas list but not sure if it'll be added to the datapack.

**Comment by Mortycio** [comment]
up

**Comment by gabriel-pinheiro** [comment]
I'll publish it by tomorrow!

**Comment by gabriel-pinheiro** [comment]
@Parilia @Mortycio version 1.3.12 is out with support for portals in The Nether and The End! (no cross-dimensional teleportation)
It's default on but there is no config to turn it off for now, it'll be added later though

You can download it here:
https://modrinth.com/datapack/warp-portals/changelog

Let me know if it works and I'll close the issue 😄

**Comment by Mortycio** [comment]
> @Parilia @Mortycio version 1.3.12 is out with support for portals in The Nether and The End! (no cross-dimensional teleportation) It's default on but there is no config to turn it off for now, it'll be added later though
> 
> You can download it here: https://modrinth.com/datapack/warp-portals/changelog
> 
> Let me know if it works and I'll close the issue 😄

It works for me! Thank you 🎉

**Comment by sternschnaube** [comment]
Thanks for this great update. Portals between dimensions would be great too 😄
